name: "sast-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci --force

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
          unzip -o dependency-check-12.1.1-release.zip

      - name: Check NVD API
        env:
          NVD_API_KEY: ${{ secrets.WORKSHOP6_NVD_API_KEY }}
        run: |
          if [ -z "$NVD_API_KEY" ]; then
            echo "NVD API key is missing"
            exit 1
          fi

          status=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "apiKey: $NVD_API_KEY" \
            "https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=1")

          echo "NVD HTTP status: $status"

          if [ "$status" != "200" ]; then
            echo "NVD API request failed"
            exit 1
          fi

      - name: Run scan with ODC
        run: |
          mkdir -p odc-report
          dependency-check/bin/dependency-check.sh --project "bitcoin" --nvdApiKey ${{ secrets.WORKSHOP6_NVD_API_KEY }} --out odc-report --scan .

      - name: Check report exists
        run: ls -lh odc-report/dependency-check-report.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sast report
          path: odc-report/dependency-check-report.html
